### ISSUE TITLE
Testing Party Bug: Share button on Schools Page

### ISSUE THREAD

**Issue by rohan-sardana** [gcivil-nyu-org/team-2-inperson#172]
Environment Information:
OS: macOS Ventura 13.0.1
Browser: Safari
Account Used: user2@test.com

Bug: Share button in lists on the Schools page does not work

**Comment by rohan-sardana** [comment]
"Sharing shortlists" was not mentioned in the "What not to test" in document till now. Just got added after I posted the issue.

**Comment by Pooja-Codes** [comment]
Currently, Profile Page has multiple features and most of them are from a UI perspective. Our team is working on making them fully functional. 

**Test Scenarios:** 
_Profile page : -_
Update first & last name
Update preferences

I hope you have considered the "Test Scenarios" section. Please accept it as "What to Test"  @rohan-sardana.

**Comment by adelaidemz** [comment]
It was not listed because it has not been implemented. Apologies for the oversight.

**Comment by rohan-sardana** [comment]
Ok, got it. Thanks!
