### ISSUE TITLE
Testing Party Bug: Discard School button

### ISSUE THREAD

**Issue by rohan-sardana** [gcivil-nyu-org/team-2-inperson#173]
Environment Information:
OS: macOS Ventura 13.0.1
Browser: Safari
Account Used: user2@test.com

Bug: Discard button on the School in the lists does not work

**Comment by Pooja-Codes** [comment]
**Test Scenarios:**
_Schools & Shortlists :_
Drag and drop functionality -> **“Delete” schools**

Make sure you are not dropping the school in an unconsidered area of the Discard/Delete section. The red indication of the mouse arrow is an unconsidered area for dropping. It varies by browser. 

https://user-images.githubusercontent.com/87775823/202821637-17c90d6a-4422-4a7e-b321-e832f4de4992.mp4

Let us know if you are considering something else as part of this issue. @rohan-sardana

**Comment by rohan-sardana** [comment]
I was actually talking about the "Discard" button that comes over the card when you click on a school in any of the lists. Please see the screenshot for reference.

I get it, as you have not saved the lists yet, maybe you have not added the delete function as well.

![Screenshot 2022-11-19 at 12.21.15 PM.png](https://images.zenhubusercontent.com/6322aa720c8cbec8cf31ffef/478e04b5-4655-47f3-9f73-ee725f5e6bbc)

**Comment by simaoalicechen** [comment]
Hi Rohan, the "discard" function has not been implemented. We will add to the not test items.
