### ISSUE TITLE
Resolve django - django rest framework incompatibilities

### ISSUE THREAD

**Issue by adelaidemz** [gcivil-nyu-org/team-2-inperson#175]

**Comment by waltage** [comment]
Still working on this. Tracking on my fork branch django-reorg

Trying to isolate the individual Django views to find the culprit; in the process of doing that I'm finding a lot of tiny issues/bugs. 

Consider this a 3-4 day project

**Comment by waltage** [comment]
I could use some help with the JavaScript client library. It's been open/requested for a few sprints now, but that client needs to be updated to handle sending the access token as a header in each request, then checking for an expiration error and automatically using the refresh token to get a new access token before retrying the original request

That has implications for the data stored in the cookie (both access and refresh tokens need to be present, and the client needs to be able to change the cookie values for the tokens on one of those update requests)

**Comment by adelaidemz** [comment]
I can work on this tomorrow; let me know if you've got some time to go over the details
