### ISSUE TITLE
Testing party: When I edit a list and use long text for list name, list edit options and other things go away.

### ISSUE THREAD

**Issue by SarthakGagdani** [gcivil-nyu-org/team-2-inperson#176]
See below Screenshot -

![image](https://user-images.githubusercontent.com/31386718/202867923-5f8580bb-6956-4f57-98cc-29f45f02494e.png)

**Comment by yalexublue** [comment]
Hey Sarthak, thanks for bringing this up this issue. I did previously show this bug during class demo (I believe it's demo 6),  thanks for reminding us! However it's not within the test range, but again thanks for reminding us.
