### ISSUE TITLE
Testing Party: Login/register not working

### ISSUE THREAD

**Issue by as14680** [gcivil-nyu-org/team-2-inperson#179]
Refer the screenshot below. When I click on signup the page throws me back to the login page. Also clicking on the login with google is also not doing anything

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/25785714/202872876-bb3d1813-c95f-433d-a62b-faee54cce03e.png">

Environment Info
Platform - MacBook Pro MAC OS 13
Browsers Tried:- Google Chrome, Safari

**Comment by Pooja-Codes** [comment]
I hope you have considered the "Test Scenarios" section. Please accept it as "What to Test". This issue is not under testing. @as14680
