### ISSUE TITLE
Testing Party: Updating User Name

### ISSUE THREAD

**Issue by as14680** [gcivil-nyu-org/team-2-inperson#180]
While updating the user name, if the character length is 10 or above the page becomes un responsive and breaks.

Refer the screenshot for reference:- 
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/25785714/202873114-4e1aa89f-61e1-408a-b313-79b52ccd26a8.png">

Environment Info:
MAC OS
Google Chrome

**Comment by Pooja-Codes** [comment]
A similar testing issue already exists. https://github.com/gcivil-nyu-org/team-2-inperson/issues/171 Please take a look.

**Comment by Pooja-Codes** [comment]
Thank you! @as14680
