### ISSUE TITLE
No forget password functionality present

### ISSUE THREAD

**Issue by Pankhurinyu** [gcivil-nyu-org/team-2-inperson#181]
There was no forget password functionality present on the website
![pic2](https://user-images.githubusercontent.com/90795848/202878713-114165cd-f65c-4913-8f79-b6db779cbfd0.png)
![pic1](https://user-images.githubusercontent.com/90795848/202878716-e0ed3e46-ddea-41e1-9e15-7f321bb09df5.png)

**Comment by Pooja-Codes** [comment]
I hope you have considered the "Test Scenarios" section. Please accept it as "What to Test". This issue is not under testing. @Pankhurinyu

**Comment by Pankhurinyu** [comment]
@Pooja-Codes Thank you for the info.
Sorry for raising this issue
