### ISSUE TITLE
Discard Button Issue

### ISSUE THREAD

**Issue by AdnanAhsanNYCity** [gcivil-nyu-org/team-2-inperson#184]
Discard button doesn't seem to work. Maybe I'm not clicking the right area, but I spent some time trying to find it but I couldn't figure it out. May need a fix.

**Comment by Pooja-Codes** [comment]
This testing party issue has already been considered and closed. https://github.com/gcivil-nyu-org/team-2-inperson/issues/173 Thank you for testing! @AdnanAhsanNYCity
