### ISSUE TITLE
Repeat High School Cards

### ISSUE THREAD

**Issue by AdnanAhsanNYCity** [gcivil-nyu-org/team-2-inperson#185]
The same high school can be added again to the same deck list, duplicating it.

**Comment by Pooja-Codes** [comment]
_Test Scenarios:_
Schools & Shortlists :
View **_(sample)_** school data
Drag and drop functionality

Currently, it is **sample** school data that will regenerate each time with the same deck. It is bound to happen. This will be completed when we will finalize our algorithm. 

Thank you for testing! @AdnanAhsanNYCity
