### ISSUE TITLE
ZenHub issue setup

### ISSUE THREAD

**Issue by adelaidemz** [gcivil-nyu-org/team-2-inperson#46]
- Add all epics to ZenHub
- Add user stories for ONE epic to ZenHub 

Note: "Epic and stories will be the ones that you will start developing so choose logically."

**Comment by simaoalicechen** [comment]
To clarify # 2 comment. 

Add issues in Epic (in the middle of the Epic page to reflect the new issues), then add ONE story + the story's acceptance + Definition of Done to ONE Issue.
