### ISSUE TITLE
Sprint Demo on 9/28

### ISSUE THREAD

**Issue by adelaidemz** [gcivil-nyu-org/team-2-inperson#47]
- Show Wiki with context diagram
- Demonstrate and explain Epics in ZenHub
- Demonstrate and explain user stories for chosen ONE epic

[Presentation Notes](https://docs.google.com/document/d/1OoedHy98RatOde11vljp899F_gw8bZePoKOYlF2RJyY/edit#)

**Comment by waltage** [comment]
There's a note that the context diagram on the wiki needs to match (exactly?) the epics (bubbles) and the stories (issues) for the selected epic; I would assume that persona tags need to match as well?  How literal do we expect "exact" to be?  Can we put a link to the chosen epic and its stories in the wiki?
