### ISSUE TITLE
Add Issue Links to wiki story

### ISSUE THREAD

**Issue by waltage** [gcivil-nyu-org/team-2-inperson#49]
see the [current first story](https://github.com/gcivil-nyu-org/team-2-inperson/wiki/High-Level-Analysis#parent--student-view-personalized-recommendations-of-high-schools) inside of View.... for an example

Do we want to link these things so they're matched (for the demo in particular)?

**Comment by adelaidemz** [comment]
Done for presentation only (View Personalized Recommendations epic)
