### ISSUE TITLE
Student & Parent - Share Choices as Recommendations (Automatic)

### ISSUE THREAD

**Issue by adelaidemz** [gcivil-nyu-org/team-2-inperson#52]
**User Story**

As a student/parent, I want Shortlist to share my preferred schools as recommendations, so that my parent/child sees the schools I like and there is a greater chance that we "match".

**Acceptance Criterion**
- When a user saves a school, it gets added to the recommendation list of their parent/student

**Comment by waltage** [comment]
Which epic is this part of? Can you tag it?

**Comment by waltage** [comment]
> 

Sorry... Ye had a different workspace that popped up that didn't have epics tagged

**Comment by waltage** [comment]
@adelaidemz 
We're leaning on moving this to the "categorize" epic #5

**Comment by waltage** [comment]
If/when this moves to "categorize," the release candidate tag should also be removed (and take it out of the zenhub demo milestone)

**Comment by adelaidemz** [comment]
Moved to "categorize" epic, removed RELEASE-CANDIDATE

**Comment by waltage** [comment]
There is a set of columns within the Recommendations model that is designated for this feature, and when we get to making Categorize live, this will be enabled; closing as completed
