### ISSUE TITLE
Parents - Recommend Chosen Schools to Students

### ISSUE THREAD

**Issue by simaoalicechen** [gcivil-nyu-org/team-2-inperson#53]
Parents allow the app to use the schools they have chosen in their lists to influence Students' choices.

**Comment by waltage** [comment]
These got reopened by zenhub when I moved them. Are these to be removed? Or will we still need to do them? Not sure where they're at

**Comment by simaoalicechen** [comment]
> These got reopened by zenhub when I moved them. Are these to be removed? Or will we still need to do them? Not sure where they're at

I would say the current pipeline "Ready For Prioritization" is good? The same with the other few you reopened.

**Comment by simaoalicechen** [comment]
> > These got reopened by zenhub when I moved them. Are these to be removed? Or will we still need to do them? Not sure where they're at
> 
> I would say the current pipeline "Ready For Prioritization" is good? The same with the other few you reopened.

Actually, Product Backlog would make more sense, since it is close to UI and right after students share shortlist.
