### ISSUE TITLE
System - Clean dataset

### ISSUE THREAD

**Issue by jainsvaibhav** [gcivil-nyu-org/team-2-inperson#59]
**User story**
As a system, I want to clean, wrangle the data, and finalize the columns to be used so that I can create the db schema accordingly and add them to the Postgres database into different tables.

**Acceptance criteria**
Columns have been selected
Data has been cleaned

**Definition of Done**
A new CSV file with clean data and selected columns.

**Comment by waltage** [comment]
This issue is showing that it is blocked right now by two issues we don't have scheduled for this sprint -- #57 and #58; 
@jainsvaibhav @adelaidemz @simaoalicechen 
Are #57 and #58 going to be added to this sprint as well? or is this issue going to be removed?
