### ISSUE TITLE
Student - Manage the Name / Icons / Colors of Shortlists

### ISSUE THREAD

**Issue by waltage** [gcivil-nyu-org/team-2-inperson#6]
**User Story**

As a student, I want Shortlist to allow me to change my online nickname, my icons for profile and shortlists and my shortlists color theme

**Acceptance Criterion**

- Student can modify their profile details such as names, icons and colors.

**Definition of Done**

- UI components of all things mentioned above is done, user will be able to make change with them.

**Comment by yalexublue** [comment]
**User Story**

As a student, I want Shortlist to allow me to change my online nickname, my icons for profile and shortlists and my shortlists color theme

**Acceptance Criterion**

Student can modify their profile details such as nickname, icons and shortlists color theme.

**Definition of Done**

UI components of all things mentioned above is done, user will be able to make change with them.
