### ISSUE TITLE
System - Write api/endpoint to get filtered recommendation from db

### ISSUE THREAD

**Issue by jainsvaibhav** [gcivil-nyu-org/team-2-inperson#63]
**User story**
As a system, I want to choose my filters(distance, rating, etc) and write an API to query and filter the db so that I can send the JSON result to the frontend.

**Acceptance criteria**
The filter criteria is chosen
The code works as intended 

**Definition of Done**
The results can be present at frontend or postman.

**Comment by waltage** [comment]
Having an HTTP method in an issue name might lock us in to a design decision we don't need to make yet, or need flexibility with. What if this one needs to be a post? Or we need to use the body, or headers for context tracking, etc

**Comment by jainsvaibhav** [comment]
sure, I understand that.

**Comment by waltage** [comment]
Updating Task List For this Sprint:

- [ ] Data Model for Recommendations (every student has a recommendation score for every school, and a few fields to store 'personalized_rank' 'viewed' 'parent_recommended' 'discarded' 'ever_accepted' etc)
- [ ] Update account/create to fill recommendations for new accounts
- [ ] Update school/create to fill recommendations for new schools
- [ ] Create endpoints for recommendations filtering
