### ISSUE TITLE
Deployment - Create first skeleton for automated deployment to AWS

### ISSUE THREAD

**Issue by waltage** [gcivil-nyu-org/team-2-inperson#72]
Base Dockerfile templates for #71 and setting the foundation of python automation for local, test, and prod deployments

The goal of this is to have a set of python executables that can be run locally, or on travis, for both build and deployment.  Testing libraries will be handled separately.

**Comment by jainsvaibhav** [comment]
hey @waltage, I can start working on this part. lmk what u are planning for this story.

**Comment by waltage** [comment]
Per my slack messages, and on the other PR about django setup, this branch below just needs to be slightly modified with the new info: https://github.com/gcivil-nyu-org/team-2-inperson/tree/72-deployment-skeletons

**Comment by waltage** [comment]
demo 1 has a working version of this (tagged in the most recent version 0.1.0).  We will keep this code out of `develop` branch for this week while the team explores other possibilities for deployment
